#!/usr/bin/env python3
"""figure-extractor, as one file — no install, no network, PyMuPDF only.

GENERATED by tools/build_standalone.py from src/figure_extractor/. Do not edit
by hand; edit the package and regenerate.

Use this when you cannot install anything: drop this file next to a PDF and run

    python figure_extractor_standalone.py extract paper.pdf --out ./figures
    python figure_extractor_standalone.py crop paper.pdf --page 5 \
        --bbox 295,245,556,475 --out fig04.png

It carries the PDF path in full — caption detection, layout analysis, quality
assessment, tiering, 300 dpi crops, manifest and contact sheet. HTML article
sources need beautifulsoup4 and stay in the installable package.
"""
from __future__ import annotations

from dataclasses import dataclass
from dataclasses import dataclass, field
from pathlib import Path
import argparse
import contextlib
import fitz
import io
import json
import math
import re
import sys
import urllib.error
import urllib.request
import zipfile

# --- from figure_extractor/utils.py -------------------------------------------


"""Source resolution: turn whatever the user pasted into a local file.

Two things went wrong here before. Only ``arxiv.org/abs/`` was normalised, so
OpenReview and ACL Anthology links never reached their PDFs; and when a
download returned something that was not a PDF, the result was silently treated
as HTML, so a blocked request surfaced far downstream as
``Unsupported or unresolved source kind: html`` instead of "the server refused
us".
"""



# Publishers routinely reject unfamiliar agents outright. Presenting a normal
# browser agent is the difference between a 200 and a 403 on most paper hosts.
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0 Safari/537.36 figure-extractor/0.2"
)

PDF = "pdf"
HTML = "html"
UNKNOWN = "unknown"


class SourceError(RuntimeError):
    """Raised when a source cannot be retrieved, with the real reason attached."""


@dataclass
class ResolvedSource:
    path: Path
    kind: str
    resolved_url: str
    note: str = ""


def is_url(source: str) -> bool:
    return source.startswith(("http://", "https://"))


def normalize_source_url(url: str) -> tuple[str, str]:
    """Rewrite a landing-page URL to the artefact it stands for.

    Returns (url, note). Users paste the page they were reading, not the file
    they want; every entry here is a landing page whose PDF lives elsewhere.
    """
    # arXiv abstract page -> PDF (version suffix preserved).
    m = re.match(r"https?://(?:www\.)?arxiv\.org/abs/([^?#]+)", url)
    if m:
        return f"https://arxiv.org/pdf/{m.group(1)}", "arxiv abs -> pdf"

    # arXiv HTML rendering: keep it, it carries the original figure bitmaps.
    if re.match(r"https?://(?:www\.)?arxiv\.org/html/", url):
        return url, "arxiv html kept (original figure assets)"

    # OpenReview forum -> PDF endpoint.
    m = re.match(r"https?://openreview\.net/forum\?(?:.*&)?id=([^&#]+)", url)
    if m:
        return f"https://openreview.net/pdf?id={m.group(1)}", "openreview forum -> pdf"

    # ACL Anthology landing page -> PDF.
    m = re.match(r"https?://(?:www\.)?aclanthology\.org/([^?#]+?)/?$", url)
    if m and not m.group(1).endswith(".pdf"):
        return f"https://aclanthology.org/{m.group(1)}.pdf", "acl anthology -> pdf"

    # Semantic Scholar / bioRxiv full-text pages expose a .full.pdf sibling.
    m = re.match(r"https?://(?:www\.)?(bio|med)rxiv\.org/content/([^?#]+?)(?:\.full)?/?$", url)
    if m and not url.endswith(".pdf"):
        return f"https://www.{m.group(1)}rxiv.org/content/{m.group(2)}.full.pdf", f"{m.group(1)}rxiv -> pdf"

    return url, ""


def sniff_kind(source: str) -> str:
    """Best guess at the artefact type from the URL or path alone."""
    lower = source.lower().split("?")[0].rstrip("/")
    if lower.endswith(".pdf") or "/pdf/" in lower or lower.endswith("/pdf"):
        return PDF
    if lower.endswith((".html", ".htm")):
        return HTML
    if is_url(source):
        # Query-string PDF endpoints (openreview.net/pdf?id=...) land here.
        if re.search(r"/pdf\b", source.lower()):
            return PDF
        return UNKNOWN
    suffix = Path(source).suffix.lower()
    if suffix == ".pdf":
        return PDF
    if suffix in {".html", ".htm"}:
        return HTML
    return UNKNOWN


def download_url(url: str, dest: Path, timeout: int = 90) -> tuple[bytes, str]:
    dest.parent.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": USER_AGENT,
            "Accept": "application/pdf,text/html;q=0.9,*/*;q=0.8",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            data = r.read()
            ctype = (r.headers.get("content-type") or "").split(";")[0].strip().lower()
    except urllib.error.HTTPError as exc:
        raise SourceError(
            f"{url} returned HTTP {exc.code} ({exc.reason}). "
            "Publisher sites commonly block automated access; download the PDF "
            "manually and pass the local path instead."
        ) from exc
    except (urllib.error.URLError, OSError) as exc:
        raise SourceError(
            f"could not fetch {url}: {exc}.\n"
            "If this runtime has no outbound network, fetch the PDF on a machine "
            "that does and re-run against the local file:\n"
            "    figure-extractor extract ./paper.pdf --out ./figures\n"
            "Cropping a local PDF needs no network and nothing beyond PyMuPDF."
        ) from exc
    dest.write_bytes(data)
    return data, ctype


def _looks_like_pdf(data: bytes) -> bool:
    return data[:5] == b"%PDF-"


def _looks_like_html(data: bytes) -> bool:
    head = data[:1024].lstrip().lower()
    return head.startswith((b"<!doctype html", b"<html", b"<?xml")) or b"<html" in head


def ensure_local_source(source: str, workdir: Path) -> ResolvedSource:
    """Resolve a user-supplied source to a local file of a known kind."""
    workdir.mkdir(parents=True, exist_ok=True)

    if not is_url(source):
        path = Path(source)
        if not path.exists():
            raise SourceError(f"no such file: {path}")
        kind = sniff_kind(source)
        if kind == UNKNOWN:
            head = path.read_bytes()[:1024]
            kind = PDF if _looks_like_pdf(head) else (HTML if _looks_like_html(head) else UNKNOWN)
        if kind == UNKNOWN:
            raise SourceError(f"cannot tell whether {path} is a PDF or an HTML document")
        return ResolvedSource(path=path, kind=kind, resolved_url=str(path))

    url, note = normalize_source_url(source)
    expected = sniff_kind(url)
    local = workdir / ("source.pdf" if expected == PDF else "source.html")
    data, ctype = download_url(url, local)

    # Content decides, not the URL — but a mismatch is worth saying out loud,
    # because "expected a PDF and got HTML" usually means we were bounced to a
    # login wall or an interstitial rather than that the paper is an HTML page.
    if _looks_like_pdf(data):
        actual = PDF
    elif _looks_like_html(data) or ctype.startswith("text/html"):
        actual = HTML
    elif ctype == "application/pdf":
        actual = PDF
    else:
        raise SourceError(
            f"{url} returned {len(data)} bytes of {ctype or 'unknown type'}, "
            "which is neither a PDF nor an HTML page"
        )

    if actual != expected and expected == PDF:
        note = (note + "; " if note else "") + (
            f"expected a PDF but the server returned {ctype or 'HTML'} — "
            "this is often a login wall, consent page or bot check"
        )
    if actual == HTML and local.suffix == ".pdf":
        local = local.with_suffix(".html")
        local.write_bytes(data)

    return ResolvedSource(path=local, kind=actual, resolved_url=url, note=note)


def safe_name(text: str) -> str:
    text = re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("_")
    return text[:120] or "file"


# --- from figure_extractor/captions.py ----------------------------------------


"""Caption label parsing.

Extraction has to be exhaustive: whatever a document calls its exhibits, they
should come out. Real corpora use far more than ``Figure N``.

* Chapter-scoped numbers — ``Figure 2.1``
* Appendix and supplementary letters — ``Figure B.1``, ``Table S3``
* Journal prefixes — ``Extended Data Fig. 1``, ``Supplementary Figure 3``
* Kinds beyond figures and tables — ``Scheme``, ``Algorithm``, ``Listing``,
  ``Box``, ``Chart``
* Nature's pipe separator — ``Fig. 1 | Overview``
* Chinese and Japanese labels — ``图 1``, ``表 2``, ``図 1``

A parser that understands only ``\\d+`` collapses distinct exhibits onto the
same identity, which downstream becomes overwritten files. The label is
therefore kept as an opaque, order-aware value rather than an int.
"""



# Journal qualifiers that make an otherwise identical number a different object:
# "Extended Data Fig. 1" is not "Fig. 1".
_PREFIX_ALTERNATIVES = (
    r"Extended\s+Data|Supplementary|Supplemental|Supp\.?|Appendix|Online|SI|附录|补充"
)

_KIND_ALTERNATIVES = (
    r"Figures?|Figs?\.?|FIGURES?|FIGS?\.?"
    r"|Tables?|Tabs?\.?|TABLES?"
    r"|Algorithms?|Algos?\.?|Algs?\.?"
    r"|Schemes?|Charts?|Listings?|Boxes|Box|Exhibits?|Plates?|Panels?"
    r"|Movies?|Videos?"
    r"|图表|插图|附图|附表|图|表|算法|方案|表格"
    r"|図表|図|表"
)

# A number token: optional letter prefix (appendix/supplement), a dotted numeric
# path, then an optional panel letter. Matches 1, 2.1, B.1, S3, A.2.1, 1a.
_NUM = r"(?:[A-Z]{1,2}[.\-]?)?\d+(?:\.\d+)*[a-z]?"

# Separators, loosest last. A single space is allowed, but a label separated
# only by a space is then screened against the cross-reference list below.
_SEP = r"[.:：、)\]]|\s*[|｜]\s*|\s[-–—]\s|\s{2,}|\s(?=\S)|$"

CAPTION_RE = re.compile(
    rf"^\s*(?:(?P<prefix>{_PREFIX_ALTERNATIVES})\s*)?"
    rf"(?P<kind>{_KIND_ALTERNATIVES})\s*"
    rf"(?P<num>{_NUM})\s*"
    rf"(?P<sep>{_SEP})",
)

# Verbs that mark a mention of an exhibit rather than its caption.
_XREF_TAIL = re.compile(
    r"^\s*(?:shows?|illustrates?|depicts?|presents?|reports?|summari[sz]es?"
    r"|compares?|gives?|lists?|plots?|visuali[sz]es?|demonstrates?|contains?"
    r"|indicates?|confirms?|suggests?|highlights?|provides?|displays?"
    r"|was|were|can|will|also|further|therefore|hence)\b",
    re.I,
)
_PUNCT_SEPARATORS = {".", ":", "：", "、", ")", "]", "|", "｜", "-", "–", "—"}

_KIND_CANON = [
    (("fig", "図", "图", "插图", "附图", "図表", "图表"), "figure"),
    (("tab", "表", "附表", "表格"), "table"),
    (("alg", "算法"), "algorithm"),
    (("scheme", "方案"), "scheme"),
    (("chart",), "chart"),
    (("listing",), "listing"),
    (("box", "boxes"), "box"),
    (("exhibit",), "exhibit"),
    (("plate",), "plate"),
    (("panel",), "panel"),
    (("movie", "video"), "media"),
]

#: Every canonical kind the parser can produce. Extraction defaults to all of
#: them: which exhibits are worth reading is a judgement for the reader, not a
#: filter to hard-code into retrieval.
ALL_KINDS = (
    "figure", "table", "algorithm", "scheme", "chart",
    "listing", "box", "exhibit", "plate", "panel", "media",
)

_PREFIX_CANON = {
    "extended data": "ed",
    "supplementary": "supp",
    "supplemental": "supp",
    "supp": "supp",
    "si": "supp",
    "补充": "supp",
    "appendix": "app",
    "附录": "app",
    "online": "online",
}


def _canon_kind(raw: str) -> str:
    r = raw.lower().rstrip(".")
    for needles, canon in _KIND_CANON:
        if any(r.startswith(n) for n in needles):
            return canon
    return r


def _canon_prefix(raw: str | None) -> str:
    if not raw:
        return ""
    r = " ".join(raw.lower().rstrip(".").split())
    return _PREFIX_CANON.get(r, re.sub(r"\W+", "", r)[:6])


@dataclass(frozen=True)
class Label:
    """A parsed caption label, e.g. ``figure`` + ``B.1``, optionally qualified."""

    kind: str
    number: str
    prefix: str = ""  # "", "ed", "supp", "app", "online"

    @property
    def slug(self) -> str:
        """Filename-safe identity. Distinct labels never collide."""
        n = self.number.replace(".", "-").replace("_", "-")
        head = f"{self.prefix}-" if self.prefix else ""
        return f"{head}{self.kind[:3]}{n}"

    @property
    def display(self) -> str:
        qualifier = {
            "ed": "Extended Data ",
            "supp": "Supplementary ",
            "app": "Appendix ",
            "online": "Online ",
        }.get(self.prefix, f"{self.prefix.capitalize()} " if self.prefix else "")
        return f"{qualifier}{self.kind.capitalize()} {self.number}"

    @property
    def sort_key(self) -> tuple:
        """Body exhibits first, then appendix/supplementary; 2.10 after 2.9."""
        m = re.match(r"^([A-Z]{1,2})[.\-]?(.*)$", self.number)
        letter, rest = (m.group(1), m.group(2)) if m else ("", self.number)
        parts: list[int] = []
        for chunk in re.split(r"[.\-]", rest):
            digits = re.sub(r"\D", "", chunk)
            if digits:
                parts.append(int(digits))
        prefix_rank = {"": 0, "online": 1, "ed": 2, "app": 3, "supp": 4}.get(self.prefix, 5)
        return (prefix_rank, self.kind, letter or "", tuple(parts), self.number)


def parse_label(text: str) -> Label | None:
    """Parse a caption label from the start of a text block.

    Returns ``None`` when the block is not a caption, including in-text cross
    references such as ``Figure 3 shows ...``.
    """
    m = CAPTION_RE.match(text or "")
    if not m:
        return None

    label = Label(
        kind=_canon_kind(m.group("kind")),
        number=m.group("num"),
        prefix=_canon_prefix(m.group("prefix")),
    )
    sep = m.group("sep").strip()
    tail = text[m.end():]

    if sep in _PUNCT_SEPARATORS:
        # A punctuated label is a caption, whatever word follows. Screening on
        # leading words instead loses every caption that opens with "The".
        return label

    # Separated only by a space, so the label may just open a sentence. Demand
    # positive evidence of a caption rather than the absence of one keyword:
    # "Fig. 6 (middle) shows the behaviors" hides its verb behind a panel
    # reference, so inspecting the first word alone lets it through.
    tail = tail.strip()
    if not tail:
        return None
    if tail.startswith("("):
        return None  # panel reference: "Fig. 6 (middle) ...", "Fig. 4 (a) ..."

    # A caption's title starts like a title — a capital, a digit, or CJK. A
    # cross reference continues the sentence, so the next word is a lowercase
    # verb or preposition. This is general; the verb list below is not, and it
    # let "Figure 3 reveals similar patterns" through because "reveals" simply
    # was not on it.
    if tail[0].islower() and tail[0].isascii():
        return None
    if any(_XREF_TAIL.match(word) for word in tail.split()[:6]):
        return None
    return label


def count_references(body_text: str, label: Label) -> int:
    """How often the body text refers to this label.

    A weak signal of how load-bearing an exhibit is: one the authors never cite
    outside its own caption is rarely central to the argument. It is a signal,
    not a verdict — deciding which figures matter is a reading judgement.
    """
    num = re.escape(label.number)
    kind_patterns = {
        "figure": r"Fig(?:ure)?s?\.?|图",
        "table": r"Tab(?:le)?s?\.?|表",
        "algorithm": r"Alg(?:orithm)?s?\.?|算法",
    }
    kind = kind_patterns.get(label.kind, re.escape(label.kind) + "s?")
    return len(re.findall(rf"(?:{kind})\s*{num}\b", body_text, flags=re.I))


# --- from figure_extractor/layout.py ------------------------------------------


"""Page layout analysis: text blocks, column detection, content margins.

The single biggest source of bad crops is treating a two-column page as if it
were one column. Everything above a caption gets unioned together, so a figure
in the right column absorbs unrelated content from the left column.

Column structure is not declared anywhere in a PDF, so we recover it from the
geometry of the text blocks: a multi-column page has a vertical *gutter* — a
band of x positions that essentially no text block crosses.
"""





@dataclass(frozen=True)
class Column:
    x0: float
    x1: float

    @property
    def width(self) -> float:
        return self.x1 - self.x0

    def contains(self, rect: fitz.Rect, tolerance: float = 6.0) -> bool:
        return rect.x0 >= self.x0 - tolerance and rect.x1 <= self.x1 + tolerance


@dataclass
class PageLayout:
    page_rect: fitz.Rect
    columns: list[Column]
    content_x0: float
    content_x1: float
    content_y0: float
    content_y1: float

    @property
    def is_multi_column(self) -> bool:
        return len(self.columns) > 1

    def band_for(self, rect: fitz.Rect) -> Column:
        """Which horizontal band an element occupies.

        An element that fits inside one column is constrained to that column. An
        element that spans the gutter is a full-width element and gets the whole
        content width. This is the key signal: **the caption itself tells us how
        wide its figure is allowed to be.**
        """
        for col in self.columns:
            if col.contains(rect):
                return col
        return Column(self.content_x0, self.content_x1)


@dataclass
class Block:
    """A text block plus the structural evidence needed to classify it."""

    rect: fitz.Rect
    text: str
    n_lines: int
    max_spans_per_line: int
    multi_span_lines: int
    median_span_gap: float = 0.0
    rotated: bool = False

    def __iter__(self):
        # Legacy unpacking support: `for rect, text in blocks`.
        yield self.rect
        yield self.text


def text_blocks(page: fitz.Page) -> list[Block]:
    """Text blocks with line/span structure, skipping image blocks."""
    out: list[Block] = []
    for b in page.get_text("dict").get("blocks", []):
        if b.get("type") != 0:
            continue
        lines = b.get("lines", []) or []
        parts = [span.get("text", "") for line in lines for span in line.get("spans", [])]
        text = " ".join("".join(parts).split())
        if not text:
            continue
        span_counts = [len(line.get("spans", []) or []) for line in lines]
        # Largest horizontal hole inside each line. Cell gutters open real gaps;
        # inline italics or math inside a sentence do not.
        line_gaps = []
        for line in lines:
            boxes = sorted(
                (sp.get("bbox") for sp in (line.get("spans", []) or []) if sp.get("bbox")),
                key=lambda b: b[0],
            )
            gaps = [boxes[i + 1][0] - boxes[i][2] for i in range(len(boxes) - 1)]
            line_gaps.append(max(gaps) if gaps else 0.0)
        line_gaps.sort()
        median_gap = line_gaps[len(line_gaps) // 2] if line_gaps else 0.0
        # Preprint servers stamp a vertical identifier down the edge of page 1.
        # It is text, but it is not part of the column grid, and letting it vote
        # on the page geometry corrupts every measurement downstream.
        dirs = [tuple(line.get("dir", (1, 0))) for line in lines]
        rotated = bool(dirs) and all(abs(dx) < 0.7 for dx, _ in dirs)
        out.append(
            Block(
                rect=fitz.Rect(b["bbox"]),
                text=text,
                n_lines=len(lines),
                max_spans_per_line=max(span_counts) if span_counts else 0,
                multi_span_lines=sum(1 for c in span_counts if c >= 2),
                median_span_gap=median_gap,
                rotated=rotated,
            )
        )
    return out


def _content_bounds(page: fitz.Page, blocks) -> tuple[float, float, float, float]:
    """Ink bounds of the page, so we stop hardcoding 35pt margins.

    Rotated blocks are excluded: a preprint server's vertical identifier down
    the edge of page 1 is real ink, but it sits outside the column grid, and
    letting it set the left bound inflates the apparent content width enough to
    break column detection downstream.
    """
    rects = [b.rect for b in blocks if not b.rotated]
    rects += [fitz.Rect(d["rect"]) for d in page.get_drawings()]
    try:
        rects += [fitz.Rect(i["bbox"]) for i in page.get_image_info(xrefs=True)]
    except Exception:
        pass
    rects = [r for r in rects if r.width > 1 and r.height > 1]
    if not rects:
        pr = page.rect
        return pr.x0 + 40, pr.x1 - 40, pr.y0 + 40, pr.y1 - 40
    return (
        max(page.rect.x0, min(r.x0 for r in rects)),
        min(page.rect.x1, max(r.x1 for r in rects)),
        max(page.rect.y0, min(r.y0 for r in rects)),
        min(page.rect.y1, max(r.y1 for r in rects)),
    )


def detect_columns(page: fitz.Page, blocks) -> list[Column]:
    """Recover column bands by locating vertical gutters.

    A gutter is a contiguous run of x positions crossed by no *narrow* text
    block. Full-width elements (spanning figures, tables, titles) legitimately
    cross the gutter, so they are excluded from the vote by ignoring blocks
    wider than 60% of the content width.
    """
    x0, x1, _, _ = _content_bounds(page, blocks)
    content_w = x1 - x0
    if content_w <= 0:
        return [Column(page.rect.x0, page.rect.x1)]

    spans = [
        (b.rect.x0, b.rect.x1)
        for b in blocks
        if not b.rotated and b.rect.width > 20 and b.rect.width < content_w * 0.60 and len(b.text) > 25
    ]
    # Not enough narrow prose to judge: assume single column.
    if len(spans) < 6:
        return [Column(x0, x1)]

    step = 2.0
    n = max(1, int(content_w / step))
    crossings = []
    for i in range(n):
        x = x0 + i * step
        crossings.append(sum(1 for a, b in spans if a < x < b))

    # A gutter is where *almost* nothing crosses, not where nothing crosses.
    # Titles, spanning figures and wide captions legitimately bridge the columns,
    # and demanding a perfectly empty channel lets a single title erase the
    # entire two-column structure of the page.
    tolerance = max(0, int(len(spans) * 0.10))

    lo, hi = int(n * 0.28), int(n * 0.72)
    best: tuple[int, int] | None = None
    run_start = None
    for i in range(lo, hi):
        if crossings[i] <= tolerance:
            if run_start is None:
                run_start = i
        else:
            if run_start is not None:
                if best is None or (i - run_start) > (best[1] - best[0]):
                    best = (run_start, i)
                run_start = None
    if run_start is not None and (best is None or (hi - run_start) > (best[1] - best[0])):
        best = (run_start, hi)

    # A real gutter is a meaningful fraction of the page, not a coincidental gap.
    if best is None or (best[1] - best[0]) * step < content_w * 0.015:
        return [Column(x0, x1)]

    gutter_x0 = x0 + best[0] * step
    gutter_x1 = x0 + best[1] * step
    left = Column(x0, gutter_x0)
    right = Column(gutter_x1, x1)
    # Reject lopsided splits: real two-column layouts are roughly symmetric.
    if min(left.width, right.width) < content_w * 0.30:
        return [Column(x0, x1)]
    return [left, right]


def consensus_columns(layouts: list[PageLayout]) -> list[Column] | None:
    """The column geometry the document as a whole agrees on.

    Column detection needs prose to measure, so a page that is mostly figure —
    exactly the page where cropping matters most — can look single-column on its
    own evidence. A paper does not change its column count page by page, so
    pages with too little text should inherit the document's answer instead of
    silently widening every crop to the full page.
    """
    votes: dict[tuple[int, int, int, int], int] = {}
    for layout in layouts:
        if not layout.is_multi_column:
            continue
        left, right = layout.columns[0], layout.columns[1]
        key = (round(left.x0 / 4), round(left.x1 / 4), round(right.x0 / 4), round(right.x1 / 4))
        votes[key] = votes.get(key, 0) + 1
    if not votes:
        return None
    key, count = max(votes.items(), key=lambda kv: kv[1])
    multi_pages = sum(1 for layout in layouts if layout.is_multi_column)
    # Demand a real majority among the pages that could be measured, so one
    # oddly-typeset page cannot impose a grid on the rest of the document.
    if count < max(2, multi_pages * 0.5):
        return None
    a, b, c, d = (v * 4 for v in key)
    return [Column(a, b), Column(c, d)]


def apply_consensus(layout: PageLayout, consensus: list[Column] | None) -> PageLayout:
    """Give an under-determined page the document's column geometry."""
    if consensus is None or layout.is_multi_column:
        return layout
    span = consensus[-1].x1 - consensus[0].x0
    page_span = layout.content_x1 - layout.content_x0
    # Only if this page's content really occupies the same measure.
    if page_span < span * 0.75 or page_span > span * 1.25:
        return layout
    layout.columns = list(consensus)
    return layout


def analyze(page: fitz.Page) -> tuple[PageLayout, list[tuple[fitz.Rect, str]]]:
    blocks = text_blocks(page)
    cx0, cx1, cy0, cy1 = _content_bounds(page, blocks)
    layout = PageLayout(
        page_rect=page.rect,
        columns=detect_columns(page, blocks),
        content_x0=cx0,
        content_x1=cx1,
        content_y0=cy0,
        content_y1=cy1,
    )
    return layout, blocks


PROSE = "prose"
TABULAR = "tabular"
LABEL = "label"


def text_role(block: Block, band_width: float) -> str:
    """Classify a text block as prose, tabular data, or a short label.

    This distinction carries real weight. Prose is a *barrier*: a crop must never
    grow through a paragraph. Tabular text is *content*: many tables in papers
    are pure text with rules, so excluding them as "long text" makes tables
    unextractable. Labels (axis ticks, legends) are content too.

    Two shape heuristics both fail on their own. "Long text = prose" swallows
    tables. "Digit-heavy = table" misses symbolic tables whose cells read
    ``O(n^2 · d)``. The load-bearing signal is *column structure*: a table's
    lines are split into several spans at repeating x offsets, while a paragraph
    is one run of text per line.
    """
    rect, text = block.rect, block.text
    if len(text) < 60:
        return LABEL

    # Impossible leading: prose needs roughly 1.2x its font size per line, so a
    # block claiming far more lines than its height allows must be laying them
    # out side by side — that is a grid of cells, not a paragraph.
    if block.n_lines >= 3 and rect.height / block.n_lines < 8.0:
        return TABULAR

    # Column structure: most lines broken into cells *separated by gutters*.
    # Span count alone is not enough — justified prose containing inline math or
    # citations is also split into many spans, and treating it as tabular
    # removes the barrier that stops a crop from running into the next section.
    if (
        block.n_lines >= 3
        and block.multi_span_lines >= max(2, int(block.n_lines * 0.6))
        and block.median_span_gap >= 6.0
    ):
        return TABULAR

    digits = sum(c.isdigit() for c in text)
    alpha = sum(c.isalpha() for c in text)
    if digits / max(1, digits + alpha) > 0.15:
        return TABULAR

    fill = rect.width / band_width if band_width > 0 else 0
    if fill > 0.70 and rect.height > 20:
        return PROSE
    if len(text) > 400:
        return PROSE
    return LABEL


def is_body_text(block: Block, band_width: float) -> bool:
    """Whether a text block is prose rather than figure content.

    The previous heuristic excluded blocks that were *long and short* — which is
    the shape of a caption, not of a paragraph. A paragraph is long and **tall**
    and fills its column, so that test let entire sections into the crop.
    """
    return text_role(block, band_width) == PROSE


# --- from figure_extractor/quality.py -----------------------------------------


"""Crop quality scoring.

A pipeline that cannot detect its own failures is worse than one that fails
loudly: every crop was previously stamped ``"status": "ok"``, including
whole-page fallbacks that contained the abstract and half a section of prose.

Nothing here inspects pixels. The evidence is geometric — how much prose the
crop swallowed, how much of the page it covers, and whether we ever found real
graphics at all.
"""




OK = "ok"
SUSPECT = "suspect"
FAILED = "failed"


@dataclass
class Verdict:
    status: str
    score: float
    reasons: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {"status": self.status, "quality_score": round(self.score, 3), "quality_reasons": self.reasons}


def _overlap_area(a: fitz.Rect, b: fitz.Rect) -> float:
    r = fitz.Rect(a) & fitz.Rect(b)
    return 0.0 if r.is_empty else r.width * r.height


def assess(
    crop: fitz.Rect,
    page_rect: fitz.Rect,
    prose_rects: list[fitz.Rect],
    had_graphics: bool,
    band_width: float,
) -> Verdict:
    """Judge one crop. Returns ok / suspect / failed with reasons."""
    reasons: list[str] = []
    score = 1.0

    area = max(1.0, crop.width * crop.height)
    page_area = max(1.0, page_rect.width * page_rect.height)

    if not had_graphics:
        # We never located a drawing or image — the bbox is a guess.
        return Verdict(FAILED, 0.0, ["no graphic primitives found above/below caption"])

    if crop.width < 24 or crop.height < 24:
        return Verdict(FAILED, 0.0, [f"degenerate crop {crop.width:.0f}x{crop.height:.0f}pt"])

    prose_area = sum(_overlap_area(crop, p) for p in prose_rects)
    prose_ratio = min(1.0, prose_area / area)
    if prose_ratio > 0.05:
        score -= min(0.75, prose_ratio * 1.6)
        reasons.append(f"body text covers {prose_ratio:.0%} of crop")

    page_ratio = area / page_area
    if page_ratio > 0.72:
        score -= 0.35
        reasons.append(f"crop covers {page_ratio:.0%} of the page")

    # A crop far wider than its own column band means the column constraint was
    # bypassed — the classic two-column bleed.
    if band_width > 0 and crop.width > band_width * 1.25:
        score -= 0.30
        reasons.append("crop is wider than its column band")

    score = max(0.0, min(1.0, score))
    if score >= 0.75:
        status = OK
    elif score >= 0.35:
        status = SUSPECT
    else:
        status = FAILED
    return Verdict(status, score, reasons)


def suggest_tier(label_kind: str, reference_count: int, verdict: Verdict, is_first: bool) -> str:
    """A *suggested* triage tier. Final tiering is a research judgement.

    Tier A  likely load-bearing: cited repeatedly in the body, or the paper's
            opening figure (which is almost always the claim figure).
    Tier B  supporting evidence worth keeping on disk.
    Tier C  keep the page reference only; do not spend a crop on it.
    """
    if verdict.status == FAILED:
        return "C"
    if is_first or reference_count >= 3:
        return "A"
    if reference_count >= 1 or label_kind == "table":
        return "B"
    return "C"


# --- from figure_extractor/contact_sheet.py -----------------------------------


# Same signal the Pillow sheet carried: a bad crop should be visible at a glance.
STATUS_COLOURS = {
    "[failed]": (0.75, 0.0, 0.0),
    "[suspect]": (0.69, 0.38, 0.0),
}
BLACK = (0.0, 0.0, 0.0)


def make_contact_sheet(
    image_paths,
    dest: Path,
    title: str = "Extracted figures",
    thumb_w: int = 360,
    cols: int = 2,
    labels: list[str] | None = None,
):
    """Render a QA sheet so a human can spot bad crops in one glance.

    Composed with PyMuPDF rather than Pillow so that cropping a PDF needs only
    the one dependency — sandboxes often ship PyMuPDF and nothing else.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    items = []
    for i, p in enumerate(image_paths):
        p = Path(p)
        try:
            pix = fitz.Pixmap(str(p))
        except Exception:
            continue
        if pix.width <= 0 or pix.height <= 0:
            continue
        caption = labels[i] if labels and i < len(labels) else p.name
        items.append((caption, p, thumb_w, max(1, round(pix.height * thumb_w / pix.width))))
    if not items:
        return None

    pad, label_h, header = 16, 32, 46
    rows = math.ceil(len(items) / cols)
    row_heights = [
        max(h for _, _, _, h in items[r * cols:(r + 1) * cols]) + label_h + pad
        for r in range(rows)
    ]
    width = cols * thumb_w + (cols + 1) * pad
    height = header + sum(row_heights) + pad

    doc = fitz.open()
    try:
        page = doc.new_page(width=width, height=height)
        page.draw_rect(page.rect, color=None, fill=(1, 1, 1))
        page.insert_text((pad, header - 20), title[:160], fontsize=9)

        y = header
        for idx, (caption, path, tw, th) in enumerate(items):
            row, col = divmod(idx, cols)
            x = pad + col * (thumb_w + pad)
            low = caption.lower()
            colour = next((c for token, c in STATUS_COLOURS.items() if token in low), BLACK)
            page.insert_text((x, y + 12), caption[:60], fontsize=8, color=colour)
            page.insert_image(fitz.Rect(x, y + label_h, x + tw, y + label_h + th), filename=str(path))
            if col == cols - 1 or idx == len(items) - 1:
                y += row_heights[row]
        # 72 dpi renders the page one pixel per point, matching the layout above.
        page.get_pixmap(dpi=72).save(dest)
    finally:
        doc.close()
    return dest


# --- from figure_extractor/pdf_cropper.py -------------------------------------


"""PDF figure/table extraction by caption-anchored, column-aware bbox inference.

Algorithm, in one paragraph: find every caption label on the page; decide which
horizontal band it lives in (one column, or the full content width when it
spans the gutter); grow a cluster of graphic primitives outward from the caption
in the conventional direction for its kind, stopping at *barriers* — other
captions and prose paragraphs; pull in nearby non-prose text (axis labels,
legends); then score the result so a bad crop reports itself as bad.
"""





# Backwards-compatible export: older callers/tests import CAPTION_RE from here.

# Vertical distance (pt) allowed between two pieces of the same figure.
MAX_INTERNAL_GAP = 42.0
# How far from the caption the figure body may start. Generous on purpose: the
# real guard against over-reaching is the barrier check, not this number.
MAX_CAPTION_GAP = 120.0


def _thicken(r: fitz.Rect, eps: float = 0.5) -> fitz.Rect:
    """Give zero-thickness rects a sliver of size.

    A perfectly horizontal rule or vertical connector has width or height of
    exactly 0, which makes ``Rect.is_empty`` true. Treating those as "nothing"
    discards table rules and every line of an attention diagram — the geometry
    is real, only its measure is zero.
    """
    r = fitz.Rect(r)
    if r.x1 - r.x0 < eps:
        r.x1 = r.x0 + eps
    if r.y1 - r.y0 < eps:
        r.y1 = r.y0 + eps
    return r


def _graphic_primitives(page: fitz.Page, layout: PageLayout) -> list[fitz.Rect]:
    rects: list[fitz.Rect] = []
    for d in page.get_drawings():
        r = _thicken(d["rect"])
        # Drop only true specks. Rejecting anything *thin* would discard axes,
        # rules and connector lines — an attention heat-map is made almost
        # entirely of long hairlines, and filtering on `width < 2 or height < 2`
        # erases the whole figure.
        if r.width < 2 and r.height < 2:
            continue
        # Header/footer rules: full-width hairlines outside the content band.
        if r.height < 3 and r.width > (layout.content_x1 - layout.content_x0) * 0.8:
            if r.y1 < layout.content_y0 + 24 or r.y0 > layout.content_y1 - 24:
                continue
        rects.append(r)
    try:
        for info in page.get_image_info(xrefs=True):
            r = _thicken(info["bbox"])
            if r.width > 2 and r.height > 2:
                rects.append(r)
    except Exception:
        pass
    return rects


def _normalise(crop: fitz.Rect, page: fitz.Page) -> fitz.Rect:
    """Clamp to the page and repair inverted edges.

    Clamping against a caption can invert an edge (content that starts below
    where it was allowed to end). Left inverted, PyMuPDF raises deep inside the
    renderer; normalised, the box is simply empty and the scorer calls it a
    failure.
    """
    return fitz.Rect(
        min(crop.x0, crop.x1), min(crop.y0, crop.y1),
        max(crop.x0, crop.x1), max(crop.y0, crop.y1),
    ) & page.rect


def _detected_tables(page: fitz.Page) -> list[fitz.Rect]:
    """Structural table bboxes from PyMuPDF's table finder.

    Heuristics over text shape cannot reliably separate a symbolic results table
    (``O(n^2 · d)``, almost no digits) from a paragraph. A dedicated table
    detector can, so prefer it and keep the heuristic only as a fallback.
    """
    # PyMuPDF prints an advisory line to stdout from inside find_tables(). The
    # CLI emits JSON on stdout, so an unsolicited banner there is not cosmetic —
    # it makes the output unparseable for anything downstream.
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            finder = page.find_tables()
    except Exception:
        return []
    out = []
    for t in getattr(finder, "tables", []) or []:
        try:
            r = fitz.Rect(t.bbox)
        except Exception:
            continue
        if not r.is_empty and r.width > 8 and r.height > 8:
            out.append(r)
    return out


def _merge_contiguous(rects: list[fitz.Rect]) -> list[fitz.Rect]:
    """Union rects that stack together vertically.

    Table detectors routinely return one logical table as several fragments
    split at horizontal rules. Taking the nearest fragment yields a 9pt sliver
    where the table should be, so stitch neighbours back together first.
    """
    if not rects:
        return []
    ordered = sorted(rects, key=lambda r: (r.y0, r.x0))
    groups = [fitz.Rect(ordered[0])]
    for r in ordered[1:]:
        cur = groups[-1]
        if r.y0 - cur.y1 <= MAX_INTERNAL_GAP:
            groups[-1] = cur | r
        else:
            groups.append(fitz.Rect(r))
    return groups


def _match_table(
    cap_rect: fitz.Rect,
    band: Column,
    tables: list[fitz.Rect],
    window: tuple[float, float],
) -> fitz.Rect | None:
    """The detected table nearest this caption, within its caption window.

    Restricting to the window before matching is what stops a caption from
    binding to a neighbour's content — a plot misdetected as a table two
    captions away is no longer even a candidate.
    """
    y_lo, y_hi = window
    inside = [
        r for r in tables
        if _in_band(r, band) and r.y1 > y_lo - 2 and r.y0 < y_hi + 2
    ]
    best: tuple[float, fitz.Rect] | None = None
    for r in _merge_contiguous(inside):
        if r.y0 >= cap_rect.y1 - 2:
            gap = r.y0 - cap_rect.y1
        elif r.y1 <= cap_rect.y0 + 2:
            gap = cap_rect.y0 - r.y1
        else:
            continue  # overlaps the caption itself
        if gap > MAX_CAPTION_GAP:
            continue
        if best is None or gap < best[0]:
            best = (gap, r)
    return None if best is None else fitz.Rect(best[1])


def _caption_window(
    cap_rect: fitz.Rect,
    other_captions: list[fitz.Rect],
    band: Column,
    layout: PageLayout,
) -> tuple[float, float]:
    """The vertical span this caption may legitimately claim.

    Bounded by the nearest caption above and below in the same band. Everything
    else on the page belongs to somebody else.
    """
    above = [o.y1 for o in other_captions if _overlaps_band(o, band) and o.y1 <= cap_rect.y0 + 2]
    below = [o.y0 for o in other_captions if _overlaps_band(o, band) and o.y0 >= cap_rect.y1 - 2]
    y_lo = max(above) + 2 if above else layout.content_y0 - 4
    y_hi = min(below) - 2 if below else layout.content_y1 + 4
    return y_lo, y_hi


def _in_band(rect: fitz.Rect, band: Column) -> bool:
    """Rect overlaps the band by most of its own width.

    Uses a floor on the denominator so a zero-width vertical line is judged by
    position rather than silently excluded by a division guard.
    """
    inter = max(0.0, min(rect.x1, band.x1) - max(rect.x0, band.x0))
    return inter / max(rect.width, 0.1) > 0.55


def _overlaps_band(rect: fitz.Rect, band: Column) -> bool:
    """Whether a rect impinges on the band at all.

    Content assignment asks "is this rect *inside* my column"; caption
    boundaries ask the weaker question "does this label sit across my column".
    A full-width caption fails the first test — less than 55% of its width lands
    in either column — yet it unquestionably bounds what a single-column figure
    beneath it may claim. Using the strict test for both is why a spanning
    caption used to bound nothing at all.
    """
    inter = max(0.0, min(rect.x1, band.x1) - max(rect.x0, band.x0))
    return inter > min(band.width, rect.width) * 0.2


def _barrier_between(barriers: list[fitz.Rect], a_edge: float, b_edge: float) -> bool:
    lo, hi = (a_edge, b_edge) if a_edge <= b_edge else (b_edge, a_edge)
    if hi - lo < 1.0:
        return False
    for b in barriers:
        if b.y0 >= lo - 1.5 and b.y1 <= hi + 1.5:
            return True
    return False


def _cluster(
    cap_rect: fitz.Rect,
    candidates: list[fitz.Rect],
    barriers: list[fitz.Rect],
    direction: str,
) -> fitz.Rect | None:
    """Grow a bbox away from the caption, stopping at gaps and barriers."""
    if direction == "up":
        pool = [r for r in candidates if r.y1 <= cap_rect.y0 + 2]
        pool.sort(key=lambda r: -r.y1)
    else:
        pool = [r for r in candidates if r.y0 >= cap_rect.y1 - 2]
        pool.sort(key=lambda r: r.y0)
    if not pool:
        return None

    first = pool[0]
    if direction == "up":
        gap0, edge_a, edge_b = cap_rect.y0 - first.y1, cap_rect.y0, first.y1
    else:
        gap0, edge_a, edge_b = first.y0 - cap_rect.y1, cap_rect.y1, first.y0
    # Distance alone is a weak signal — journals leave 60pt of air between a
    # figure and its caption. What actually separates "my figure" from "someone
    # else's content" is whether prose or another caption sits in between.
    if gap0 > MAX_CAPTION_GAP:
        return None
    if gap0 > 0 and _barrier_between(barriers, edge_a, edge_b):
        return None

    cluster = fitz.Rect(first)
    for r in pool[1:]:
        if direction == "up":
            gap = cluster.y0 - r.y1
            edge_a, edge_b = cluster.y0, r.y1
        else:
            gap = r.y0 - cluster.y1
            edge_a, edge_b = cluster.y1, r.y0
        if gap > MAX_INTERNAL_GAP:
            break
        if gap > 0 and _barrier_between(barriers, edge_a, edge_b):
            break
        cluster |= r
    return cluster


def _clamp_between_captions(
    crop: fitz.Rect,
    cap_rect: fitz.Rect,
    other_captions: list[fitz.Rect],
    band: Column,
) -> fitz.Rect:
    """Confine a crop to the space between its caption and the neighbouring ones.

    A hard invariant beats another heuristic here: **a crop must never contain a
    different caption**. Distance limits, gap limits and barrier tests are all
    approximations that a real page eventually defeats; "you may not cross your
    neighbour's label" is exact, and it is what stops a figure from swallowing
    the table above it.
    """
    out = fitz.Rect(crop)
    above = [o for o in other_captions if _overlaps_band(o, band) and o.y1 <= cap_rect.y0 + 2]
    below = [o for o in other_captions if _overlaps_band(o, band) and o.y0 >= cap_rect.y1 - 2]
    if above:
        out.y0 = max(out.y0, max(o.y1 for o in above) + 2)
    if below:
        out.y1 = min(out.y1, min(o.y0 for o in below) - 2)
    return out


def _closer_caption_exists(
    cluster: fitz.Rect,
    cap_rect: fitz.Rect,
    other_captions: list[fitz.Rect],
    band: Column,
    own_gap: float,
) -> bool:
    """Whether some other caption sits nearer to this content than we do.

    Content belongs to its nearest caption. Without this rule a caption placed
    below its own table happily claims the figure underneath it, and two
    captions end up describing the same pixels.
    """
    own = max(0.0, own_gap)
    for o in other_captions:
        if not _overlaps_band(o, band) or o == cap_rect:
            continue
        if o.y0 >= cluster.y1:
            d = o.y0 - cluster.y1
        elif o.y1 <= cluster.y0:
            d = cluster.y0 - o.y1
        else:
            return True  # another caption sits inside the cluster
        if d < own - 2:
            return True
    return False


def _attach_labels(
    cluster: fitz.Rect,
    blocks: list[tuple[fitz.Rect, str]],
    band: Column,
    cap_rect: fitz.Rect,
    direction: str,
    barriers: list[fitz.Rect],
) -> fitz.Rect:
    """Pull in axis labels / legends that sit just outside the graphic hull."""
    halo = fitz.Rect(cluster)
    halo.x0 -= 22
    halo.x1 += 22
    halo.y0 -= 24
    halo.y1 += 24
    out = fitz.Rect(cluster)
    for block in blocks:
        r = block.rect
        if not _in_band(r, band):
            continue
        if is_body_text(block, band.width):
            continue
        if direction == "up" and r.y1 > cap_rect.y0 + 2:
            continue
        if direction == "down" and r.y0 < cap_rect.y1 - 2:
            continue
        if not r.intersects(halo):
            continue
        edge_a = out.y0 if r.y1 <= out.y0 else out.y1
        edge_b = r.y1 if r.y1 <= out.y0 else r.y0
        if _barrier_between(barriers, edge_a, edge_b):
            continue
        out |= r
    return out


def _infer_bbox(
    page: fitz.Page,
    layout: PageLayout,
    blocks: list[tuple[fitz.Rect, str]],
    primitives: list[fitz.Rect],
    cap_rect: fitz.Rect,
    label: Label,
    other_captions: list[fitz.Rect],
    margin: float,
    tables: list[fitz.Rect],
) -> tuple[fitz.Rect, bool, Column, list[fitz.Rect]]:
    """Infer one crop box. Returns (crop, had_graphics, band, prose_rects)."""
    band = layout.band_for(cap_rect)
    window = _caption_window(cap_rect, other_captions, band, layout)

    prose = [b.rect for b in blocks if _in_band(b.rect, band) and is_body_text(b, band.width)]
    barriers = [r for r in other_captions if _overlaps_band(r, band)] + prose

    # Structural detection wins outright when it fires.
    if label.kind == "table":
        matched = _match_table(cap_rect, band, tables, window)
        if matched is not None:
            crop = fitz.Rect(matched)
            crop.x0 = max(band.x0 - 2, crop.x0 - margin)
            crop.x1 = min(band.x1 + 2, crop.x1 + margin)
            crop.y0 -= margin
            crop.y1 += margin
            crop = _normalise(crop, page)
            return crop, not crop.is_empty, band, prose

    y_lo, y_hi = window

    def _within(r: fitz.Rect) -> bool:
        return r.y1 > y_lo - 2 and r.y0 < y_hi + 2

    graphics = [r for r in primitives if _in_band(r, band) and _within(r)]
    # Tables are frequently pure text with rules, so their body *is* text.
    if label.kind in {"table", "algorithm"}:
        content = graphics + [
            b.rect for b in blocks
            if _in_band(b.rect, band)
            and _within(b.rect)
            and b.rect != cap_rect
            and text_role(b, band.width) in {TABULAR, LABEL}
        ]
    else:
        content = graphics

    # Conventional direction first (tables caption-above, figures caption-below),
    # but fall back to the other side rather than guessing blindly.
    primary = "down" if label.kind in {"table", "algorithm"} else "up"
    secondary = "up" if primary == "down" else "down"

    # Evaluate both sides and let the evidence decide. Committing to the
    # conventional side as soon as it yields *anything* is what makes a table
    # captioned below its body swallow the next figure instead: content must
    # belong to the caption nearest to it, not to whichever caption asks first.
    uncontested: list[tuple[float, str, fitz.Rect]] = []
    contested: list[tuple[float, str, fitz.Rect]] = []
    for direction in (primary, secondary):
        cluster = _cluster(cap_rect, content, barriers, direction)
        if cluster is None:
            continue
        gap = (cap_rect.y0 - cluster.y1) if direction == "up" else (cluster.y0 - cap_rect.y1)
        entry = (max(0.0, gap), direction, cluster)
        if _closer_caption_exists(cluster, cap_rect, other_captions, band, gap):
            contested.append(entry)
        else:
            uncontested.append(entry)

    # Ownership is a preference, not a veto: when every side is contested we
    # still return the best available box rather than nothing, and let the
    # scorer judge it.
    pool = uncontested or contested
    best: tuple[fitz.Rect, str] | None = None
    if pool:
        # Smallest gap wins; the conventional side breaks near-ties.
        pool.sort(key=lambda c: (round(c[0] / 10.0), 0 if c[1] == primary else 1, c[0]))
        _, direction, cluster = pool[0]
        best = (_attach_labels(cluster, blocks, band, cap_rect, direction, barriers), direction)

    had_graphics = True
    if best is None:
        had_graphics = False
        # Last resort: a conservative box on the caption's conventional side.
        # Always guessing "above" produces a 2pt sliver for a table captioned at
        # the top of a page. Marked as a failure by the scorer either way — never
        # silently reported as a good crop.
        if primary == "down":
            bottom = min(layout.content_y1, cap_rect.y1 + 260)
            crop = fitz.Rect(band.x0, cap_rect.y1 + 2, band.x1, bottom)
        else:
            top = max(layout.content_y0, cap_rect.y0 - 260)
            crop = fitz.Rect(band.x0, top, band.x1, cap_rect.y0 - 2)
    else:
        crop, direction = best
        crop = fitz.Rect(crop)
        crop.x0 = max(band.x0 - 2, crop.x0 - margin)
        crop.x1 = min(band.x1 + 2, crop.x1 + margin)
        if direction == "up":
            crop.y0 = max(layout.content_y0 - 2, crop.y0 - margin)
            crop.y1 = min(cap_rect.y0 - 2, crop.y1 + margin)
        else:
            crop.y0 = max(cap_rect.y1 + 2, crop.y0 - margin)
            crop.y1 = min(layout.content_y1 + 2, crop.y1 + margin)

    crop = _clamp_between_captions(crop, cap_rect, other_captions, band)
    crop = _normalise(crop, page)
    if crop.is_empty or crop.width < 4 or crop.height < 4:
        had_graphics = False
    return crop, had_graphics, band, prose


def _find_captions(doc: fitz.Document):
    """All caption blocks in reading order, keyed by (kind, number).

    Duplicate labels are kept when they occur on different pages: papers really
    do restart numbering in appendices, and collapsing them loses figures.
    """
    found = []
    for pi, page in enumerate(doc):
        layout, blocks = analyze(page)
        page_caps = []
        for rect, text in blocks:
            label = parse_label(text)
            if label:
                page_caps.append({"label": label, "rect": rect, "text": text})
        found.append({"page_index": pi, "page": page, "layout": layout, "blocks": blocks, "captions": page_caps})

    # Second pass: pages that could not measure their own columns inherit the
    # document's, so a figure-heavy page does not get a full-width band by
    # default.
    consensus = consensus_columns([f["layout"] for f in found])
    for f in found:
        f["layout"] = apply_consensus(f["layout"], consensus)
    return found


def extract_pdf_figures(
    pdf_path: Path,
    out_dir: Path,
    dpi: int = 300,
    margin: float = 8,
    make_sheet: bool = True,
    make_zip: bool = True,
    kinds: tuple[str, ...] = ALL_KINDS,
    tiers: tuple[str, ...] = ("A", "B", "C"),
) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    doc = fitz.open(pdf_path)
    body_text = "\n".join(p.get_text() for p in doc)
    pages = _find_captions(doc)

    items = []
    seen_slugs: dict[str, int] = {}
    first_of_kind: set[str] = set()

    for pinfo in pages:
        page = pinfo["page"]
        layout = pinfo["layout"]
        blocks = pinfo["blocks"]
        caps = pinfo["captions"]
        if not caps:
            continue
        primitives = _graphic_primitives(page, layout)
        cap_rects = [c["rect"] for c in caps]
        wants_tables = any(c["label"].kind == "table" for c in caps) and "table" in kinds
        tables = _detected_tables(page) if wants_tables else []

        for cap in caps:
            label: Label = cap["label"]
            if label.kind not in kinds:
                continue
            others = [r for r in cap_rects if r is not cap["rect"]]
            crop, had_graphics, band, prose = _infer_bbox(
                page, layout, blocks, primitives, cap["rect"], label, others, margin, tables
            )
            verdict = assess(crop, page.rect, prose, had_graphics, band.width)
            refs = count_references(body_text, label)
            is_first = label.kind not in first_of_kind
            first_of_kind.add(label.kind)
            tier = suggest_tier(label.kind, refs, verdict, is_first)

            slug = label.slug
            seen_slugs[slug] = seen_slugs.get(slug, 0) + 1
            if seen_slugs[slug] > 1:
                slug = f"{slug}_dup{seen_slugs[slug]}"

            entry = {
                "label": label.display,
                "kind": label.kind,
                "number": label.number,
                "page": pinfo["page_index"] + 1,
                "caption": cap["text"],
                "bbox": [round(v, 2) for v in (crop.x0, crop.y0, crop.x1, crop.y1)],
                "column_layout": "multi" if layout.is_multi_column else "single",
                "spans_columns": layout.is_multi_column and band.width > (layout.content_x1 - layout.content_x0) * 0.8,
                "referenced_in_body": refs,
                "suggested_tier": tier,
                "method": "caption-anchored-column-aware-crop",
                "dpi": dpi,
                "_sort": label.sort_key,
                "_slug": slug,
                "_crop": crop,
                "_page": page,
            }
            entry.update(verdict.as_dict())
            items.append(entry)

    items.sort(key=lambda e: (e["page"], e["_sort"]))

    figures = []
    image_paths = []
    skipped = 0
    for e in items:
        if e["suggested_tier"] not in tiers:
            skipped += 1
            e.pop("_crop"), e.pop("_page"), e.pop("_sort"), e.pop("_slug")
            e["output"] = None
            e["skipped_reason"] = f"tier {e['suggested_tier']} not in requested tiers {list(tiers)}"
            figures.append(e)
            continue
        crop = e.pop("_crop")
        page = e.pop("_page")
        e.pop("_sort")
        slug = e.pop("_slug")
        out_path = out_dir / f"{slug}_p{e['page']:02d}.png"
        try:
            if crop.is_empty or crop.width < 4 or crop.height < 4:
                raise ValueError(f"degenerate crop {crop.width:.1f}x{crop.height:.1f}pt")
            pix = page.get_pixmap(dpi=dpi, clip=crop, alpha=False)
            pix.save(out_path)
        except Exception as exc:
            e["output"] = None
            e["status"] = "failed"
            e["quality_score"] = 0.0
            e["quality_reasons"] = list(e.get("quality_reasons", [])) + [f"render failed: {exc}"]
            figures.append(e)
            continue
        e["output"] = str(out_path)
        image_paths.append((out_path, f"{e['label']}  [{e['status']}]"))
        figures.append(e)

    counts = {
        "total": len(figures),
        "rendered": len(image_paths),
        "skipped_by_tier": skipped,
        "ok": sum(1 for f in figures if f["status"] == "ok"),
        "suspect": sum(1 for f in figures if f["status"] == "suspect"),
        "failed": sum(1 for f in figures if f["status"] == "failed"),
        "figures": sum(1 for f in figures if f["kind"] == "figure"),
        "tables": sum(1 for f in figures if f["kind"] == "table"),
    }
    manifest = {
        "source": str(pdf_path),
        "kind": "pdf",
        "dpi": dpi,
        "pages": len(doc),
        "counts": counts,
        "figures": figures,
    }
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    if make_sheet and image_paths:
        make_contact_sheet(
            [p for p, _ in image_paths],
            out_dir / "contact_sheet.jpg",
            title=f"{pdf_path.name} — {counts['rendered']} crops "
            f"({counts['ok']} ok / {counts['suspect']} suspect / {counts['failed']} failed)",
            labels=[lbl for _, lbl in image_paths],
        )
    if make_zip and image_paths:
        zip_path = out_dir / "figures.zip"
        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
            for p, _ in image_paths:
                z.write(p, p.name)
            z.write(out_dir / "manifest.json", "manifest.json")
            sheet = out_dir / "contact_sheet.jpg"
            if sheet.exists():
                z.write(sheet, "contact_sheet.jpg")
        manifest["zip"] = str(zip_path)
    return manifest


def crop_manual(pdf_path: Path, page: int, bbox: str, out_path: Path, dpi: int = 300) -> dict:
    doc = fitz.open(pdf_path)
    vals = [float(x) for x in bbox.split(",")]
    if len(vals) != 4:
        raise ValueError("bbox must be x0,y0,x1,y1")
    if not 1 <= page <= doc.page_count:
        raise ValueError(f"page {page} out of range (document has {doc.page_count} pages)")
    rect = fitz.Rect(*vals)
    pix = doc[page - 1].get_pixmap(dpi=dpi, clip=rect, alpha=False)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pix.save(out_path)
    return {"page": page, "bbox": vals, "output": str(out_path), "dpi": dpi, "status": "ok"}


# --------------------------------------------------------------------------
# Command line
# --------------------------------------------------------------------------


def _parse_csv(value, allowed, what):
    if value.strip().lower() == "all":
        return tuple(allowed)
    picked = tuple(v.strip() for v in value.split(",") if v.strip())
    bad = [v for v in picked if v not in allowed]
    if bad:
        raise SystemExit(f"unknown {what}: {', '.join(bad)} (choose from {', '.join(allowed)})")
    return picked


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="figure_extractor_standalone",
        description="Extract figures and tables from a PDF. PyMuPDF only, no install.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    ex = sub.add_parser("extract", help="Extract from a PDF file or URL")
    ex.add_argument("source", help="Local PDF path, or a PDF/arXiv URL if this runtime has network")
    ex.add_argument("--out", default="figures")
    ex.add_argument("--dpi", type=int, default=300)
    ex.add_argument("--margin", type=float, default=8)
    ex.add_argument("--zip", action="store_true")
    ex.add_argument("--no-contact-sheet", action="store_true")
    ex.add_argument("--kinds", default="all", help=f"Comma-separated: {', '.join(ALL_KINDS)}, or 'all'")
    ex.add_argument("--tiers", default="all", help="Comma-separated: A, B, C, or 'all'")

    cr = sub.add_parser("crop", help="Manually crop a PDF page by bbox")
    cr.add_argument("pdf")
    cr.add_argument("--page", type=int, required=True)
    cr.add_argument("--bbox", required=True, help="x0,y0,x1,y1 in PDF points")
    cr.add_argument("--out", required=True)
    cr.add_argument("--dpi", type=int, default=300)

    args = p.parse_args(argv)
    try:
        if args.cmd == "crop":
            manifest = crop_manual(Path(args.pdf), page=args.page, bbox=args.bbox,
                                   out_path=Path(args.out), dpi=args.dpi)
        else:
            out = Path(args.out)
            src = ensure_local_source(args.source, out / ".work")
            if src.kind != PDF:
                raise SystemExit(
                    f"{args.source!r} resolved to {src.kind!r}, not a PDF. This single-file "
                    "build handles PDFs only; use the installable package for HTML sources."
                )
            manifest = extract_pdf_figures(
                src.path, out, dpi=args.dpi, margin=args.margin,
                make_sheet=not args.no_contact_sheet, make_zip=args.zip,
                kinds=_parse_csv(args.kinds, ALL_KINDS, "kind"),
                tiers=_parse_csv(args.tiers, ("A", "B", "C"), "tier"),
            )
    except SourceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
