#!/usr/bin/env python3
"""Stitch the PDF path into one dependency-free file.

Runtimes that cannot `pip install` — no network, no package index, no write
access to site-packages — can still crop figures if they have PyMuPDF, but only
if the tool arrives as a single file they can write and run. This generates that
file from the package so the two cannot drift apart.

    python tools/build_standalone.py            # regenerate
    python tools/build_standalone.py --check    # fail if the committed copy is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "figure_extractor"
DEST = ROOT / "standalone" / "figure_extractor_standalone.py"

# The reduced extractor is embedded in SKILL.md itself, because a runtime with
# no network cannot fetch any file from this repo — including the standalone.
BOOTSTRAP = ROOT / "bootstrap" / "minimal_extractor.py"
NO_RASTER = ROOT / "bootstrap" / "no_rasterizer_extractor.py"
SKILL = ROOT / "SKILL.md"
BEGIN = ("<!-- BEGIN EMBEDDED EXTRACTOR: generated from "
         "bootstrap/minimal_extractor.py by tools/build_standalone.py -->")
END = "<!-- END EMBEDDED EXTRACTOR -->"
BEGIN_NR = ("<!-- BEGIN EMBEDDED NO-RASTERIZER EXTRACTOR: generated from "
            "bootstrap/no_rasterizer_extractor.py by tools/build_standalone.py -->")
END_NR = "<!-- END EMBEDDED NO-RASTERIZER EXTRACTOR -->"

# Dependency order: later modules may use names defined by earlier ones.
# html_extractor is included now that it parses with the standard library.
MODULES = ["utils", "captions", "layout", "quality", "contact_sheet",
           "pdf_cropper", "minisoup", "html_extractor"]

HEADER = '''#!/usr/bin/env python3
"""figure-extractor, as one file — no install, no network, PyMuPDF only.

GENERATED by tools/build_standalone.py from src/figure_extractor/. Do not edit
by hand; edit the package and regenerate.

Use this when you cannot install anything: drop this file next to a PDF and run

    python figure_extractor_standalone.py extract paper.pdf --out ./figures
    python figure_extractor_standalone.py crop paper.pdf --page 5 \\
        --bbox 295,245,556,475 --out fig04.png

It carries the whole pipeline — caption detection, layout analysis, quality
assessment, tiering, 300 dpi crops, manifest and contact sheet — and handles
HTML sources too, including a saved page whose images are inline data: URIs.
Give it a local .html file and it needs no network at all.
"""
from __future__ import annotations
'''

FOOTER = '''

# --------------------------------------------------------------------------
# Command line
# --------------------------------------------------------------------------


def _parse_csv(value, allowed, what):
    if value.strip().lower() == "all":
        return tuple(allowed)
    picked = tuple(v.strip() for v in value.split(",") if v.strip())
    bad = [v for v in picked if v not in allowed]
    if bad:
        raise SystemExit(f"unknown {what}: {', '.join(bad)} (choose from {', '.join(allowed)})")
    return picked


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="figure_extractor_standalone",
        description="Extract figures and tables from a PDF. PyMuPDF only, no install.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    ex = sub.add_parser("extract", help="Extract from a PDF or HTML file, or a URL")
    ex.add_argument("source", help="Local PDF/HTML path, or a URL if this runtime has network")
    ex.add_argument("--out", default="figures")
    ex.add_argument("--dpi", type=int, default=300)
    ex.add_argument("--margin", type=float, default=8)
    ex.add_argument("--zip", action="store_true")
    ex.add_argument("--no-contact-sheet", action="store_true")
    ex.add_argument("--kinds", default="all", help=f"Comma-separated: {', '.join(ALL_KINDS)}, or 'all'")
    ex.add_argument("--tiers", default="all", help="Comma-separated: A, B, C, or 'all'")

    cr = sub.add_parser("crop", help="Manually crop a PDF page by bbox")
    cr.add_argument("pdf")
    cr.add_argument("--page", type=int, required=True)
    cr.add_argument("--bbox", required=True, help="x0,y0,x1,y1 in PDF points")
    cr.add_argument("--out", required=True)
    cr.add_argument("--dpi", type=int, default=300)

    args = p.parse_args(argv)
    try:
        if args.cmd == "crop":
            manifest = crop_manual(Path(args.pdf), page=args.page, bbox=args.bbox,
                                   out_path=Path(args.out), dpi=args.dpi)
        else:
            out = Path(args.out)
            src = ensure_local_source(args.source, out / ".work")
            if src.note:
                print(f"note: {src.note}", file=sys.stderr)
            if src.kind == HTML:
                manifest = extract_html_figures(
                    src.path, out,
                    base_url=src.resolved_url if is_url(src.resolved_url) else None,
                    make_sheet=not args.no_contact_sheet,
                )
                print(json.dumps(manifest, indent=2, ensure_ascii=False))
                return 0
            if src.kind != PDF:
                raise SystemExit(f"{args.source!r} is neither a PDF nor an HTML document")
            manifest = extract_pdf_figures(
                src.path, out, dpi=args.dpi, margin=args.margin,
                make_sheet=not args.no_contact_sheet, make_zip=args.zip,
                kinds=_parse_csv(args.kinds, ALL_KINDS, "kind"),
                tiers=_parse_csv(args.tiers, ("A", "B", "C"), "tier"),
            )
    except SourceError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

RELATIVE_IMPORT = re.compile(r"^from \.(\w*) import (.+)$")
TOP_LEVEL_IMPORT = re.compile(r"^(?:import |from [A-Za-z_])")


def build() -> str:
    imports: list[str] = ["import argparse", "import sys"]
    body: list[str] = []

    for name in MODULES:
        source = (PKG / f"{name}.py").read_text(encoding="utf-8")
        chunk: list[str] = []
        pending_relative = False
        for line in source.splitlines():
            if line.startswith("from __future__ import"):
                continue
            rel = RELATIVE_IMPORT.match(line)
            if rel:
                # The module is inlined instead — but an alias would be lost with
                # the import, so re-bind it: `from .m import A as B` -> `B = A`.
                spec = rel.group(2).strip()
                pending_relative = spec.endswith("(")
                for part in spec.strip("()").split(","):
                    bits = part.split("#")[0].split()
                    if len(bits) == 3 and bits[1] == "as":
                        chunk.append(f"{bits[2]} = {bits[0]}")
                continue
            if pending_relative:
                pending_relative = not line.strip().startswith(")")
                continue
            if TOP_LEVEL_IMPORT.match(line):
                if line not in imports:
                    imports.append(line)
                continue
            chunk.append(line)
        body.append(f"# --- from figure_extractor/{name}.py " + "-" * max(4, 48 - len(name)))
        body.append("\n".join(chunk).strip("\n"))

    parts = [HEADER, "\n".join(sorted(set(imports))), "", "\n\n\n".join(body), FOOTER]
    return "\n".join(parts).rstrip("\n") + "\n"


def build_skill() -> str:
    """SKILL.md with the embedded extractor refreshed from bootstrap/."""
    text = SKILL.read_text(encoding="utf-8")
    start, end = text.index(BEGIN), text.index(END)
    code = BOOTSTRAP.read_text(encoding="utf-8").rstrip("\n")
    block = f"{BEGIN}\n\n```python\n{code}\n```\n\n"
    text = text[:start] + block + text[end:]

    start, end = text.index(BEGIN_NR), text.index(END_NR)
    code = NO_RASTER.read_text(encoding="utf-8").rstrip("\n")
    block = f"{BEGIN_NR}\n\n```python\n{code}\n```\n\n"
    return text[:start] + block + text[end:]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Exit non-zero if the committed file is out of date")
    args = ap.parse_args()

    artifacts = [(DEST, build()), (SKILL, build_skill())]
    if args.check:
        stale = [dest for dest, want in artifacts
                 if (dest.read_text(encoding="utf-8") if dest.exists() else "") != want]
        if stale:
            names = ", ".join(str(d.relative_to(ROOT)) for d in stale)
            print(f"{names} stale — run: python tools/build_standalone.py", file=sys.stderr)
            return 1
        print("generated artifacts are up to date")
        return 0

    for dest, want in artifacts:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(want, encoding="utf-8")
        print(f"wrote {dest.relative_to(ROOT)} ({len(want.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
